"""Render PR curve and reliability diagram from the calibration JSON.

Outputs:
  docs/figures/pr_curve.png          — precision-recall curve (Track B)
  docs/figures/reliability_diagram.png — calibration reliability diagram

Tolerates absence of model/recurrence_clf_v1_calibration.json (prints a note
and exits 0 — the file is generated by `make calibrate`).

Tolerates absence of matplotlib (prints a note and exits 0 — install with
`pip install matplotlib` to render figures).

Usage:
    python scripts/plot_metrics.py
    make plots
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CAL_FILE = REPO / "model" / "recurrence_clf_v1_calibration.json"
FIGURES_DIR = REPO / "docs" / "figures"


def _require_matplotlib():
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        return plt
    except ImportError:
        return None


def plot_pr_curve(cal: dict, plt, out_dir: Path) -> None:
    pr = cal.get("pr_curve", {})
    precision = pr.get("precision", [])
    recall = pr.get("recall", [])
    if not precision or not recall:
        print("[plot_metrics] no pr_curve data in calibration JSON — skipping PR curve")
        return

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.step(recall, precision, where="post", color="#1f4e79", linewidth=1.8)
    ap = cal.get("summary", {}).get("average_precision")
    label = f"AP = {ap:.3f}" if ap is not None else None
    if label:
        ax.plot([], [], color="#1f4e79", label=label)
        ax.legend(loc="upper right", fontsize=10)
    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_title("FloodWatch.PH Track B — Precision-Recall (event-disjoint holdout)")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.05)
    ax.grid(True, alpha=0.3)

    out = out_dir / "pr_curve.png"
    fig.savefig(out, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"[plot_metrics] wrote {out}")


def plot_reliability(cal: dict, plt, out_dir: Path) -> None:
    rel = cal.get("reliability_diagram", {})
    mean_pred = rel.get("mean_predicted_prob", [])
    frac_pos = rel.get("fraction_of_positives", [])
    if not mean_pred or not frac_pos:
        print("[plot_metrics] no reliability_diagram data in calibration JSON — skipping")
        return

    fig, ax = plt.subplots(figsize=(5, 5))
    ax.plot([0, 1], [0, 1], linestyle="--", color="#aaaaaa", linewidth=1, label="Perfect calibration")
    ax.plot(mean_pred, frac_pos, marker="o", color="#c0392b", linewidth=1.8, label="recurrence_clf_v1")
    ax.set_xlabel("Mean predicted probability")
    ax.set_ylabel("Fraction of positives")
    ax.set_title("FloodWatch.PH Track B — Reliability Diagram (event-disjoint holdout)")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(loc="upper left", fontsize=9)
    ax.grid(True, alpha=0.3)

    out = out_dir / "reliability_diagram.png"
    fig.savefig(out, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"[plot_metrics] wrote {out}")


def main() -> int:
    plt = _require_matplotlib()
    if plt is None:
        print(
            "[plot_metrics] matplotlib not installed — install with "
            "`pip install matplotlib` to render figures. Exiting 0."
        )
        return 0

    if not CAL_FILE.exists():
        print(
            f"[plot_metrics] {CAL_FILE} not found — run `make calibrate` first. "
            "Exiting 0."
        )
        return 0

    try:
        cal = json.loads(CAL_FILE.read_text())
    except Exception as exc:
        print(f"[plot_metrics] cannot parse {CAL_FILE}: {exc}", file=sys.stderr)
        return 1

    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    plot_pr_curve(cal, plt, FIGURES_DIR)
    plot_reliability(cal, plt, FIGURES_DIR)
    print("[plot_metrics] done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
